### ISSUE TITLE
Interface bug

### ISSUE THREAD

**Issue by wqwangwei** [kbterm/kubeterm#11]
### Platform

macOS

### What happened?

![bug](https://github.com/user-attachments/assets/2728faa4-e766-413f-a875-4451b1f8a369)
![界面乱码](https://github.com/user-attachments/assets/be56d020-9b62-4274-955d-39b804498cc1)

External screens don't have this error

### App version

Kubeterm:Version 1.4.0 (101)
macOS: MacBook Pro (Retina, 13-inch, Early 2015),macOs Monterey 12.7.6 (21H1320)

**Comment by daimg** [comment]
Thanks for report the issue.

How often does this happen?  Did it happen after kubeterm run for a while? 

It seems some kind of memory issue, perhaps the machine is under system memory pressure. Could you please check system memory usage when this issue happened?

If the system is in normal, could you please have a try on former release v1.3.4 to find if same issue exist?

**Comment by wqwangwei** [comment]
macbook: MacBook Pro M4,macos Monterey 15.1 The image is no longer problematic.

But the previously submitted deployment did not respond after the restart.

App version
Kubeterm:Version 1.4.0 (101)
macbook: MacBook Pro M4,macos Monterey 15.1

**Comment by daimg** [comment]
> But the previously submitted deployment did not respond after the restart.

Could you please provide more info about "not respond"?
Do you mean kubeterm UI  is not responding, or you failed to restart existed deployment, or some else?

**Comment by wqwangwei** [comment]
> > 但是之前提交的部署重启之后没有任何反应。
> 
> 您能否提供有关“无响应”的更多信息？ 您的意思是 kubeterm UI 没有响应，或者您无法重新启动现有部署，还是其他原因？

![kubeterm](https://github.com/user-attachments/assets/07e1224b-98a2-4db3-8d7b-139898726fb6)

**Comment by daimg** [comment]
Thanks for providing the info.
It will be fixed it in next release.

**Comment by wqwangwei** [comment]
> Thanks for providing the info. It will be fixed it in next release.

The issue has been fixed, and the application can now be restarted normally.
