### ISSUE TITLE
Manually define list of Namespaces per Cluster

### ISSUE THREAD

**Issue by rbcb-bedag** [kbterm/kubeterm#13]
### Platform

Windows / MacOS

### What would you like to be added?

In our clusters (managed by our own data center guys) we don't have the permission to list all namespaces.
In k8slens/OpenLens there is the functionality to manually define namespaces per Clusters. So the IDE then didn't fetched all namespaces but used this list.

With this new functionality we could then (hopefully) use kubeterm in environments with missing permissions for listing namespaces.

### Why is this needed?

Because lack of permissions for namespaces

**Comment by daimg** [comment]
Thanks for the request.

We will enable this functionality in next release.  (It was temporarily disabled in a previous release for some reason)

**Comment by rbcb-bedag** [comment]
@daimg I've seen, that you have build the release v1.4.2 with this new feature, thank you very much !

But sadly since v1.4.1 there are no windows binaries (eg. .exe) built by the release, so i cannout test it on windows.
Could you maybe re-build the release with the windows binary included ?

Thank you
