### ISSUE TITLE
Add substring search in pod logs

### ISSUE THREAD

**Issue by ashcl0ud712** [kbterm/kubeterm#5]
### Platform

IOS

### What would you like to be added?

Hi!
Either filtering out logs matching the substring or highlighting and letting jump between matching logs would be useful
Preferably both, thanks for considering

**Comment by daimg** [comment]
Thanks for suggestion. It could be supported in next release.

**Comment by daimg** [comment]
Both are supported in v1.3.4 now, please update from App Store.

**Comment by ashcl0ud712** [comment]
Yup, just checked it out, looks good
Thanks! Closing this
